# Generated by Django 5.2.7 on 2025-10-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgblivros', '0002_autor_remove_livro_ano_publicacao_alter_livro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
    ]
