# Generated by Django 5.2.7 on 2025-10-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgblivros', '0003_livro_ano_publicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='data_nasciemento',
            new_name='data_nascimento',
        ),
    ]
